"""Initial schema

Revision ID: 2aa567e2a95e
Revises: 
Create Date: 2019-07-02 10:47:45.994755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa567e2a95e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing',
    sa.Column('id', sa.String(), server_default=sa.text('uuid_generate_v1()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subthing',
    sa.Column('id', sa.String(), server_default=sa.text('uuid_generate_v1()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('thing_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subthing')
    op.drop_table('thing')
    # ### end Alembic commands ###
